name: Build and test Sync-Trees

on:
  push:
    branches:
      - sync-trees

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./4-Parallel-Trees

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: ./gradlew build

    - name: Test
      run: ./gradlew test
